name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # ✅ Fixes the 403 issue when creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract release notes from CHANGELOG.md
        id: extract_changelog
        run: |
          changelog=$(awk "/^## ${{ env.TAG_NAME }}/,/^##/" CHANGELOG.md | sed '1d;$d')
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: ${{ env.RELEASE_BODY }}
