name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract release notes from CHANGELOG.md
        id: extract_changelog
        run: |
          TAG="${{ env.TAG_NAME }}"
          # Extract section for current tag until next '##' or end of file
          changelog=$(awk -v tag="## $TAG" '
            $0 == tag {flag=1; next}
            /^## / && flag {exit}
            flag { print }
          ' CHANGELOG.md)

          # Save to environment variable
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Zip extension folder
        run: zip -r extension.zip extension

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: ${{ env.RELEASE_BODY }}
          files: extension.zip
